[package]
name = "handle-errors"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.3"
reqwest-middleware = "0.3.0"
tracing = { version = "0.1.40", features = ["log"] }
warp = "0.3.6"
sqlx = "0.7.4"
rust-argon2 = "2.1.0"